In [10]:
import pickle
import pandas as pd

In [11]:
version = 'v1'
geno_test_file = geno_test_file = '../processed_data/test_geno_with_8_m_avg_all_data_{}.pkl'.format(version)
geno_training_file = '../processed_data/tr_geno_with_8_m_avg_all_data_{}.pkl'.format(version)
geno_validation_file = '../processed_data/val_geno_with_8_m_avg_all_data_{}.pkl'.format(version)
geno_unqiue_test_file = '../processed_data/test_geno_unique_env_with_8_m_avg_all_data_{}.pkl'.format(version)

In [12]:
df = pd.DataFrame()

In [13]:
with open(geno_test_file, 'rb') as file:
    data = pickle.load(file)
    
data.shape

(12978, 4069)

In [14]:
df.append(data)

/var/folders/k7/ksx513m54v14grw8wqbbgj9w0000gn/T/ipykernel_62348/233211020.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append(data)

,CID,SID,GID,2A_15449240,2A_18359259,2A_2800711,2B_5042248,2A_18058916,2A_4942949,3B_261620049,...,Cycle,Value,Occ,nursary,HARVEST_FINISHING_DATE,HARVEST_STARTING_DATE,SOWING_DATE,start_date,end_date,weather
0,568630,33,GID7400769,0.302138,0.438644,0.294080,0.403931,0.340551,0.294998,0.430540,...,2017,5.6190,122,50IBWSN,2018-05-15,May 15 2018,2017-11-15,2017-09-15,2018-05-15,"[0.0935483870967742, 80.12258064516128, 36.145..."
1,568630,33,GID7400769,0.302138,0.438644,0.294080,0.403931,0.340551,0.294998,0.430540,...,2017,6.8100,114,50IBWSN,2018-05-10,May 10 2018,2017-12-21,2017-10-21,2018-06-21,"[0.19677419354838707, 79.11290322580645, 42.99..."
2,568630,33,GID7400769,0.302138,0.438644,0.294080,0.403931,0.340551,0.294998,0.430540,...,2017,6.7620,121,50IBWSN,2018-05-10,May 10 2018,2017-11-29,2017-09-29,2018-05-29,"[0.6870967741935484, 81.19032258064517, 45.212..."
3,568630,33,GID7400769,0.302138,0.438644,0.294080,0.403931,0.340551,0.294998,0.430540,...,2017,9.3330,35,50IBWSN,2018-07-15,Jul 15 2018,2017-11-23,2017-09-23,2018-05-23,"[0.22580645161290322, 54.41290322580647, 23.36..."
4,568630,33,GID7400769,0.302138,0.438644,0.294080,0.403931,0.340551,0.294998,0.430540,...,2019,6.1110,47,40ESWYT,2020-04-08,Apr 8 2020,2019-11-19,2019-09-19,2020-05-19,"[10.341666666666667, 97.00833333333333, 74.658..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12973,537330,26,GID6922446,0.202805,0.447300,0.209509,0.517199,0.173455,0.208738,0.098425,...,2012,2.5465,15,1WYCYT,2013-03-25,Mar 25 2013,2012-11-20,2012-09-20,2013-05-20,"[0.0032258064516129032, 69.63225806451611, 30...."
12974,537327,28,GID6922453,0.202805,0.447300,0.209509,0.517199,0.173455,0.208738,0.471035,...,2012,3.5510,14,1WYCYT,2013-03-15,Mar 15 2013,2012-11-20,2012-09-20,2013-05-20,"[0.0032258064516129032, 69.63225806451611, 30...."
12975,537327,28,GID6922453,0.202805,0.447300,0.209509,0.517199,0.173455,0.208738,0.471035,...,2012,3.5510,15,1WYCYT,2013-03-25,Mar 25 2013,2012-11-20,2012-09-20,2013-05-20,"[0.0032258064516129032, 69.63225806451611, 30...."
12976,420697,57,GID6056237,0.202805,0.447300,0.209509,0.517199,0.173455,0.208738,0.471035,...,2012,3.6225,14,1WYCYT,2013-03-15,Mar 15 2013,2012-11-20,2012-09-20,2013-05-20,"[0.0032258064516129032, 69.63225806451611, 30...."
12977,420697,57,GID6056237,0.202805,0.447300,0.209509,0.517199,0.173455,0.208738,0.471035,...,2012,3.6225,15,1WYCYT,2013-03-25,Mar 25 2013,2012-11-20,2012-09-20,2013-05-20,"[0.0032258064516129032, 69.63225806451611, 30...."

In [15]:
with open(geno_training_file, 'rb') as file:
    data = pickle.load(file)
    
data.shape

df.append(data)

FileNotFoundError: [Errno 2] No such file or directory: '../processed_data/tr_geno_with_8_m_avg_all_data_v1.pkl'

In [ ]:
with open(geno_validation_file, 'rb') as file:
    data = pickle.load(file)
    
data.shape

df.append(data)

In [ ]:
with open(geno_unqiue_test_file, 'rb') as file:
    data = pickle.load(file)
    
data.shape

df.append(data)